/**
 * Config file template generation for `agentdoor init`.
 *
 * Generates:
 *   - agentdoor.config.ts (TypeScript configuration)
 *   - .well-known/agentdoor.json (Discovery document)
 *   - .well-known/agent-card.json (A2A compatibility)
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface ScopeTemplate {
  id: string;
  description: string;
  price?: string;
  rateLimit?: string;
}

interface X402Template {
  network: string;
  currency: string;
  paymentAddress: string;
  facilitator?: string;
}

export interface ConfigTemplateOptions {
  framework: string;
  serviceName: string;
  serviceDescription: string;
  scopes: ScopeTemplate[];
  pricing?: Record<string, string>;
  x402?: X402Template;
  rateLimit?: { default: string };
}

export interface DiscoveryTemplateOptions {
  serviceName: string;
  serviceDescription: string;
  scopes: ScopeTemplate[];
  x402?: X402Template;
  rateLimit?: { default: string };
}

export interface A2ACardOptions {
  serviceName: string;
  serviceDescription: string;
  scopes: ScopeTemplate[];
}

// ---------------------------------------------------------------------------
// agentdoor.config.ts generator
// ---------------------------------------------------------------------------

/**
 * Generate the content of `agentdoor.config.ts`.
 */
export function generateConfigFile(options: ConfigTemplateOptions): string {
  const { framework, serviceName, serviceDescription, scopes, pricing, x402 } = options;

  const importPath = getPackageName(framework);

  const scopeLines = scopes
    .map((s) => {
      const parts = [`      id: "${s.id}"`, `      description: "${s.description}"`];
      if (s.price) parts.push(`      price: "${s.price}"`);
      if (s.rateLimit) parts.push(`      rateLimit: "${s.rateLimit}"`);
      return `    {\n${parts.join(",\n")},\n    }`;
    })
    .join(",\n");

  let pricingBlock = "";
  if (pricing && Object.keys(pricing).length > 0) {
    const pricingEntries = Object.entries(pricing)
      .map(([key, value]) => `    "${key}": "${value}"`)
      .join(",\n");
    pricingBlock = `\n  pricing: {\n${pricingEntries},\n  },`;
  }

  let x402Block = "";
  if (x402) {
    const x402Parts = [
      `    network: "${x402.network}"`,
      `    currency: "${x402.currency}"`,
      `    paymentAddress: "${x402.paymentAddress}"`,
    ];
    if (x402.facilitator) {
      x402Parts.push(`    facilitator: "${x402.facilitator}"`);
    }
    x402Block = `\n  x402: {\n${x402Parts.join(",\n")},\n  },`;
  }

  const rateLimitBlock = `\n  rateLimit: {\n    default: "${options.rateLimit?.default ?? "1000/hour"}",\n  },`;

  return `/**
 * AgentDoor Configuration
 *
 * Generated by \`agentdoor init\`.
 * Edit this file to customize your AgentDoor integration.
 *
 * Docs: https://agentdoor.dev/docs/configuration
 */

import type { AgentDoorConfig } from "${importPath}";

const config: AgentDoorConfig = {
  serviceName: "${serviceName}",
  serviceDescription: "${serviceDescription}",

  scopes: [
${scopeLines},
  ],${pricingBlock}${x402Block}${rateLimitBlock}

  // Lifecycle callbacks (optional)
  // onAgentRegistered: async (agent) => {
  //   console.log(\`Agent registered: \${agent.id}\`);
  // },
  // onAgentAuthenticated: async (agent) => {
  //   console.log(\`Agent authenticated: \${agent.id}\`);
  // },
};

export default config;
`;
}

// ---------------------------------------------------------------------------
// .well-known/agentdoor.json generator
// ---------------------------------------------------------------------------

/**
 * Generate the discovery document JSON object.
 */
export function generateDiscoveryJson(
  options: DiscoveryTemplateOptions,
): Record<string, unknown> {
  const doc: Record<string, unknown> = {
    agentdoor_version: "1.0",
    service_name: options.serviceName,
    service_description: options.serviceDescription,
    registration_endpoint: "/agentdoor/register",
    auth_endpoint: "/agentdoor/auth",
    scopes_available: options.scopes.map((s) => ({
      id: s.id,
      description: s.description,
      ...(s.price ? { price: s.price } : {}),
      ...(s.rateLimit ? { rate_limit: s.rateLimit } : {}),
    })),
    auth_methods: ["ed25519-challenge", "x402-wallet", "jwt"],
    rate_limits: {
      registration: "10/hour",
      default: options.rateLimit?.default ?? "1000/hour",
    },
  };

  if (options.x402) {
    doc.payment = {
      protocol: "x402",
      version: "2.0",
      networks: [options.x402.network],
      currency: [options.x402.currency],
      facilitator: options.x402.facilitator ?? "https://x402.org/facilitator",
    };
  }

  doc.companion_protocols = {
    a2a_agent_card: "/.well-known/agent-card.json",
  };

  return doc;
}

// ---------------------------------------------------------------------------
// .well-known/agent-card.json generator (A2A compat)
// ---------------------------------------------------------------------------

/**
 * Generate a Google A2A agent card. This allows A2A-compatible agents to
 * discover this service.
 *
 * Spec: https://google.github.io/A2A/
 */
export function generateA2ACard(
  options: A2ACardOptions,
): Record<string, unknown> {
  return {
    name: options.serviceName,
    description: options.serviceDescription,
    url: "https://your-domain.com",
    version: "1.0",
    capabilities: {
      streaming: false,
      pushNotifications: false,
    },
    skills: options.scopes.map((s) => ({
      id: s.id,
      name: s.id.replace(".", " "),
      description: s.description,
    })),
    authentication: {
      schemes: ["agentdoor-ed25519", "bearer"],
      agentdoor: {
        discovery: "/.well-known/agentdoor.json",
        registration: "/agentdoor/register",
      },
    },
    defaultInputModes: ["application/json"],
    defaultOutputModes: ["application/json"],
  };
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function getPackageName(framework: string): string {
  switch (framework) {
    case "nextjs":
      return "@agentdoor/next";
    case "express":
      return "@agentdoor/express";
    case "hono":
      return "@agentdoor/hono";
    default:
      return "@agentdoor/core";
  }
}
